name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build
      run: ./build.sh

  test_file:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build
      run: ./build.sh
    - name: test_file
      run: cd tests && g++ file.cpp -fPIC ../libNyx.so -I ../lib/FileManager/inc -I ../lib/FormatParser/inc && LD_PRELOAD=../libNyx.so ./a.out

  test_file_2:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build
      run: ./build.sh
    - name: test_file_2
      run: cd tests && g++ file2.cpp -fPIC ../libNyx.so -I ../lib/FileManager/inc -I ../lib/FormatParser/inc && LD_PRELOAD=../libNyx.so ./a.out

  test_loader:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build
      run: ./build.sh
    - name: test_loader
      run: cd tests && g++ loader.cpp -fPIC ../libNyx.so -I ../lib/FileManager/inc -I ../lib/FormatParser/inc && LD_PRELOAD=../libNyx.so ./a.out

  test_parser:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build
      run: ./build.sh
    - name: test_parser
      run: cd tests && g++ parser.cpp -fPIC ../libNyx.so -I ../lib/FileManager/inc -I ../lib/FormatParser/inc && LD_PRELOAD=../libNyx.so ./a.out

  test_json:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build
      run: ./build.sh
    - name: test_json
      run: cd tests && g++ json.cpp -fPIC ../libNyx.so -I ../lib/FileManager/inc -I ../lib/FormatParser/inc && LD_PRELOAD=../libNyx.so ./a.out

  test_xml:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build
      run: ./build.sh
    - name: test_xml
      run: cd tests && g++ xml.cpp -fPIC ../libNyx.so -I ../lib/FileManager/inc -I ../lib/FormatParser/inc && LD_PRELOAD=../libNyx.so ./a.out
