name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build
      run: ./build.sh

  test_file:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build
      run: ./build.sh
    - name: test_file
      run: cd .github/workflows && g++ file.cpp -fPIC ../../libNyx.so -I ../../lib/FileManager/inc -I ../../lib/FormatParser/inc && LD_PRELOAD=../../libNyx.so  ./a.out
